# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            TablePlus
tagline:          'A Chrome Extension'
description:      'A <a href="https://www.google.com/chrome/index.html" target="_blank">Chrome</a> extension to process clipboard text and render markup usable in Jira.'
url:              http://mgualdron.github.io/TablePlus
baseurl:          /

author:
  name:           'Miguel Gualdron'
  url:            https://github.com/mgualdron

gems:             [jekyll-paginate, jekyll-gist]
paginate:         5

# Custom vars
version:          0.0.5

github:           [Repository metadata]
  repo:           https://github.com/mgualdron/TablePlus
